### ISSUE TITLE
Missing hatom data in Google Webmaster Tools

### ISSUE THREAD

**Issue by MichiMunich** [chemiker/e.nigma-2015#2]
Hi,

if i check my wordpress blog running with your theme in google webmaster tools, i geht the missing hatom data information for "entry-title", "updated" and "author".
I was able to solve this issue with a function in my functions.php of the child theme:

/\* Add hatom data */
function add_enigma_hatom_data($content) {
    $title = get_the_title();
    $mod_time = get_the_modified_time('F jS, Y');
    $author = get_the_author();
if (is_home() || is_singular() || is_archive() ) {
        $content .= '<div class="hatom-extra" style="display:none;visibility:hidden;"><span class="entry-title">'.$title.'</span> was last modified: <span class="updated"> '.$mod_time.'</span> by <span class="author vcard"><span class="fn">'.$author.'</span></span></div>';
    }
    return $content;
    }
add_filter('the_content', 'add_enigma_hatom_data');

Maybe you can integrate this or something similar in your theme.

Best regards
Michi

**Comment by chemiker** [comment]
Hi Michi,

sorry for the ridiculously late reply. I'm glad you found a solution for your problem and that you also provided a fix.

However, I think I will not include this fix in the theme because in my opinion it is in [plugin territory](https://make.wordpress.org/themes/handbook/review/required/#plugins). WordPress themes are usually only thought to provide styling and do not modify content if not absolutely necessary.

Best

Alex
